<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta HTTP-EQUIV="Pragma" CONTENT="no-cache"/><meta HTTP-EQUIV="Expires" CONTENT="-1"/>
<link rel="shortcut icon" href="images/favicon.png"/><link rel="icon" href="images/favicon.png"/>
<title>软件中心 - codexproxyd</title>
<link rel="stylesheet" type="text/css" href="index_style.css"/><link rel="stylesheet" type="text/css" href="form_style.css"/><link rel="stylesheet" type="text/css" href="usp_style.css"/><link rel="stylesheet" type="text/css" href="css/element.css"><link rel="stylesheet" type="text/css" href="/device-map/device-map.css"><link rel="stylesheet" type="text/css" href="/res/softcenter.css">
<script type="text/javascript" src="/js/jquery.js"></script><script type="text/javascript" src="/state.js"></script><script type="text/javascript" src="/popup.js"></script><script type="text/javascript" src="/validator.js"></script><script type="text/javascript" src="/general.js"></script><script type="text/javascript" src="/res/softcenter.js"></script>
<style>
#loading_block3{margin:10px auto;width:85%;font-size:12pt;white-space:pre-line}.ks_info{line-height:24px}.ks_info code{font-family:Consolas,monospace;background:rgba(0,0,0,.18);padding:2px 6px;border-radius:4px}textarea.ks_payload,textarea.ks_runtime_log{width:98%;background:rgba(0,0,0,.2);color:#fff;border:1px solid rgba(255,255,255,.2);padding:10px;font-family:Consolas,monospace;resize:vertical}textarea.ks_payload{min-height:180px}textarea.ks_runtime_log{min-height:220px}input.readonly_field{width:320px!important}input[type=button]:focus{outline:none}.ks_badge{display:inline-block;min-width:72px;padding:2px 10px;margin-right:8px;border-radius:999px;font-size:12px;font-weight:bold;text-align:center;color:#fff}.ks_badge_success{background:#2e8b57}.ks_badge_warn{background:#d08a00}.ks_badge_error{background:#b94a48}.ks_badge_info{background:#5b7fa3}.ks_status_detail{display:inline-block;vertical-align:middle}.ks_inline_row,.ks_usage_actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.ks_inline_row .button_gen{min-width:60px}.ks_usage_meta{color:rgba(255,255,255,.75);font-size:12px}.ks_usage_empty{padding:4px 0;color:rgba(255,255,255,.75)}.ks_usage_panel_shell{max-height:420px;overflow:auto;border:1px solid rgba(255,255,255,.08);border-radius:6px;background:rgba(0,0,0,.08)}.ks_usage_table{width:100%;border-collapse:collapse;table-layout:fixed}.ks_usage_table th,.ks_usage_table td{padding:10px;border-bottom:1px solid rgba(255,255,255,.08);vertical-align:top}.ks_usage_table th{text-align:left;position:sticky;top:0;background:rgba(61,78,85,.96);z-index:1}.ks_usage_table tbody tr:last-child td{border-bottom:none}.ks_usage_index{width:40px;color:rgba(255,255,255,.65);text-align:center}.ks_usage_account{min-width:260px}.ks_usage_email{display:block;font-family:Consolas,monospace;word-break:break-all}.ks_usage_planline{display:block;margin-top:6px}.ks_plan_badge{display:inline-block;min-width:56px;padding:2px 8px;border-radius:999px;border:1px solid rgba(255,255,255,.18);background:rgba(91,127,163,.35);font-size:12px;font-weight:bold;text-transform:uppercase;letter-spacing:.04em}.ks_usage_value{display:block;white-space:nowrap;font-weight:bold}.ks_usage_reset{display:block;margin-top:2px;color:rgba(255,255,255,.7);font-size:12px}.ks_usage_status{width:180px}.ks_usage_hint{display:block;color:rgba(255,255,255,.6);font-size:12px}.ks_usage_error{display:block;margin-top:4px;color:#ffb4b4;font-size:12px}
</style>
<script>
var db_codexproxyd={},status_cache={},status_poll_timer=null,runtime_log_timer=null,status_request_inflight=false,log_request_inflight={},action_log_poll_timer=null,action_log_poll_inflight=false,action_log_failures=0,action_log_started_at=0,action_status_refresh_timer=null,action_close_timer=null,current_action_name="",current_action_success_message="",pending_api_key_value="";
function init(){show_menu(menu_hook);set_skin();bindVisibilityEvents();get_dbus_data(function(){get_disks();get_run_status();refresh_runtime_log();refreshAuditLog();refreshErrorLog();});}
function set_skin(){var s='<% nvram_get("sc_skin"); %>';if(s){$("#app").attr("skin",s);}}
function menu_hook(){tabtitle[tabtitle.length-1]=new Array("","codexproxyd","__INHERIT__");tablink[tablink.length-1]=new Array("","Module_codexproxyd.asp","NULL");}
function reload_Soft_Center(){location.href="/Module_Softcenter.asp";}
function pageIsVisible(){return typeof document.hidden=="undefined"||!document.hidden;}
function bindVisibilityEvents(){if(!document.addEventListener){return;}document.addEventListener("visibilitychange",function(){if(pageIsVisible()){get_run_status();refresh_runtime_log(true);}else{scheduleRuntimeLogRefresh(0);scheduleStatusPoll(0);}});}
function scheduleStatusPoll(ms){if(status_poll_timer){clearTimeout(status_poll_timer);status_poll_timer=null;}if(ms>0){status_poll_timer=setTimeout(get_run_status,ms);}}
function get_dbus_data(onDone){$.ajax({type:"GET",url:"/_api/codexproxyd",dataType:"json",success:function(d){db_codexproxyd=d.result[0]||{};conf_to_obj();if(onDone){onDone();}},error:function(){if(onDone){onDone();}}});}
function conf_to_obj(){E("codexproxyd_enable").checked=db_codexproxyd["codexproxyd_enable"]=="1";E("codexproxyd_disk_path_selected").value=db_codexproxyd["codexproxyd_disk_path_selected"]||"";if(db_codexproxyd["codexproxyd_image_ref"]){E("codexproxyd_image_ref").value=db_codexproxyd["codexproxyd_image_ref"];}E("codexproxyd_default_model").value="gpt-5.4";ensureSelectValue("codexproxyd_default_effort",db_codexproxyd["codexproxyd_default_effort"]||"high");ensureSelectValue("codexproxyd_audit_log_level",db_codexproxyd["codexproxyd_audit_log_level"]||"basic");refresh_paths();}
function ensureSelectValue(id,value){var s=E(id),v=value||"";if(!s){return;}for(var i=0;i<s.options.length;i++){if(s.options[i].value==v){s.value=v;return;}}if(v){var o=document.createElement("option");o.value=v;o.text=v+" (custom)";s.appendChild(o);s.value=v;}}
function formatDiskSize(bytes){var u=["B","KB","MB","GB","TB"],s=bytes,i=0;while(s>=1024&&i<u.length-1){s/=1024;i++;}return s.toFixed(2)+" "+u[i];}
function ensureDiskPathOption(path,label){var s=E("codexproxyd_disk_path_selected"),i=0,o=null,v=String(path||"").replace(/^\s+|\s+$/g,"");if(!s||!v){return;}for(i=0;i<s.options.length;i++){if(s.options[i].value==v){if(label){s.options[i].text=label;}return;}}o=document.createElement("option");o.value=v;o.text=label||v+" (saved)";s.appendChild(o);}
function deriveDiskPathFromDockrootBin(dockrootBin){var text=String(dockrootBin||"").replace(/^\s+|\s+$/g,""),suffix="/DockRootBin/DockRoot";if(!text||text=="-"||text.length<=suffix.length){return "";}if(text.substring(text.length-suffix.length)==suffix){return text.substring(0,text.length-suffix.length);}return "";}
function syncDiskPathSelection(){var s=E("codexproxyd_disk_path_selected"),resolved=resolveDiskPathSelected();if(!s){return "";}if(resolved){ensureDiskPathOption(resolved,resolved+" (saved)");s.value=resolved;}else if(s.options.length==1&&s.options[0].value){s.value=s.options[0].value;resolved=s.options[0].value;}return String(s.value||resolved||"").replace(/^\s+|\s+$/g,"");}
function get_disks(){require(['/require/modules/diskList.js'],function(diskList){var l=[],s=E("codexproxyd_disk_path_selected"),i=0,j=0,p=null,m="",t="";if(s){s.options.length=0;}try{l=diskList.list()||[];}catch(error){l=[];}for(i=0;i<l.length;++i){for(j=0;j<l[i].partition.length;++j){p=l[i].partition[j];m='/tmp/mnt/'+p.partName;t=m+"|"+p.format+"|"+formatDiskSize(p.size);ensureDiskPathOption(m,t);}}syncDiskPathSelection();refresh_paths();});}
function refresh_paths(){var d=syncDiskPathSelection();E("data_dir").innerHTML=d?d+"/codex-proxyd-data":"-";E("dockroot_bin").innerHTML=d?d+"/DockRootBin/DockRoot":"-";E("runtime_log_path").innerHTML=d?d+"/DockRootData/codexproxyd/ruri.log":"-";E("audit_log_path").innerHTML=d?d+"/codex-proxyd-data/logs/access.jsonl":"-";E("error_log_path").innerHTML=d?d+"/codex-proxyd-data/logs/error.jsonl":"-";}
function deriveDiskPathFromDataDir(dataDir){var text=String(dataDir||"").replace(/^\s+|\s+$/g,""),suffix="/codex-proxyd-data";if(!text||text=="-"||text.length<=suffix.length){return "";}if(text.substring(text.length-suffix.length)==suffix){return text.substring(0,text.length-suffix.length);}return "";}
function resolveDiskPathSelected(){var directValue="",savedValue="",statusValue="",dockrootValue="",displayValue="";if(E("codexproxyd_disk_path_selected")){directValue=String(E("codexproxyd_disk_path_selected").value||"").replace(/^\s+|\s+$/g,"");}if(directValue){return directValue;}savedValue=String((db_codexproxyd&&db_codexproxyd["codexproxyd_disk_path_selected"])||"").replace(/^\s+|\s+$/g,"");if(savedValue){return savedValue;}statusValue=deriveDiskPathFromDataDir(status_cache&&status_cache.dataDir);if(statusValue){return statusValue;}dockrootValue=deriveDiskPathFromDockrootBin(status_cache&&status_cache.dockrootBin);if(dockrootValue){return dockrootValue;}displayValue=deriveDiskPathFromDataDir(E("data_dir")?E("data_dir").innerHTML:"");if(displayValue){return displayValue;}return deriveDiskPathFromDockrootBin(E("dockroot_bin")?E("dockroot_bin").innerHTML:"");}
function currentDataDirValue(){var statusValue=String((status_cache&&status_cache.dataDir)||"").replace(/^\s+|\s+$/g,""),savedValue=String((db_codexproxyd&&db_codexproxyd["codexproxyd_data_dir_value"])||"").replace(/^\s+|\s+$/g,""),displayValue=String(E("data_dir")?E("data_dir").innerHTML:"").replace(/^\s+|\s+$/g,""),resolvedDisk=resolveDiskPathSelected(),selectedDataDir=resolvedDisk?resolvedDisk+"/codex-proxyd-data":"";if(resolvedDisk&&savedValue&&deriveDiskPathFromDataDir(savedValue)&&deriveDiskPathFromDataDir(savedValue)!=resolvedDisk){return selectedDataDir;}if(resolvedDisk&&statusValue&&deriveDiskPathFromDataDir(statusValue)&&deriveDiskPathFromDataDir(statusValue)!=resolvedDisk){return selectedDataDir;}if(statusValue&&statusValue!="-"){return statusValue;}if(savedValue&&savedValue!="-"){return savedValue;}if(displayValue&&displayValue!="-"){return displayValue;}return selectedDataDir;}
function currentImageRefValue(){var directValue="",statusValue="",savedValue="";if(E("codexproxyd_image_ref")){directValue=String(E("codexproxyd_image_ref").value||"").replace(/^\s+|\s+$/g,"");}statusValue=String((status_cache&&status_cache.imageRef)||"").replace(/^\s+|\s+$/g,"");savedValue=String((db_codexproxyd&&db_codexproxyd["codexproxyd_image_ref"])||"").replace(/^\s+|\s+$/g,"");return directValue||statusValue||savedValue||"";}
function attachChunkedField(fields,key,value){var text=String(value||""),chunkSize=3000,chunks=[],index=0,suffix="";fields[key]="";fields[key+"_chunks"]="0";if(!text){return;}if(text.length<=chunkSize){fields[key]=text;return;}for(index=0;index<text.length;index+=chunkSize){chunks.push(text.substring(index,index+chunkSize));}fields[key+"_chunks"]=String(chunks.length);for(index=0;index<chunks.length;index++){suffix=("0000"+index).slice(-4);fields[key+"_"+suffix]=chunks[index];}}
function parseApiObjectResult(rawResult){if(typeof rawResult=="string"){return JSON.parse(rawResult||"{}");}if(rawResult&&typeof rawResult=="object"){return rawResult;}return {};}
function get_run_status(){if(!pageIsVisible()){scheduleStatusPoll(15000);return;}if(status_request_inflight){return;}status_request_inflight=true;var id=parseInt(Math.random()*1e8),postData={id:id,method:"codexproxyd_status.sh",params:[],fields:""};$.ajax({type:"POST",cache:false,url:"/_api/",data:JSON.stringify(postData),dataType:"json",success:function(r){status_request_inflight=false;try{var result=parseApiObjectResult(r.result);status_cache=result||{};render_status(result||{});if(maybeFinishActionFromStatus(result)){return;}scheduleStatusPoll(1e4);}catch(error){setStatusBadge("error","异常");E("status").innerHTML="状态解析失败";scheduleRuntimeLogRefresh(0);scheduleStatusPoll(5e3);}},error:function(){status_request_inflight=false;setStatusBadge("error","异常");E("status").innerHTML="状态读取失败";scheduleRuntimeLogRefresh(0);scheduleStatusPoll(5e3);}});}
function setStatusBadge(kind,text){var b=E("status_badge");b.className="ks_badge ks_badge_"+kind;b.innerHTML=text;}
function formatLastImportText(r){if(r.lastImportAt){return r.lastImportAt;}if(r.accountsPresent){return "已存在（外部导入）";}return "未导入";}
function escapeHtml(value){return String(value===null||typeof value=="undefined"?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");}
function pad2(value){return value<10?"0"+value:String(value);}
function formatUsagePercent(value){var number=Number(value);if(!isFinite(number)){return "--";}var normalized=Math.round(number*10)/10;if(Math.abs(normalized-Math.round(normalized))<0.05){normalized=Math.round(normalized);}return normalized+"%";}
function formatUsageResetTime(value){var number=Number(value);if(!isFinite(number)||number<=0){return "--";}var date=new Date(number*1000);if(isNaN(date.getTime())){return "--";}return date.getFullYear()+"/"+pad2(date.getMonth()+1)+"/"+pad2(date.getDate())+" "+pad2(date.getHours())+":"+pad2(date.getMinutes())+":"+pad2(date.getSeconds());}
function formatUsageCell(percent,resetAt){return '<span class="ks_usage_value">'+escapeHtml(formatUsagePercent(percent))+'</span><span class="ks_usage_reset">重置: '+escapeHtml(formatUsageResetTime(resetAt))+"</span>";}
function renderAccountsUsage(accounts){var list=$.isArray(accounts)?accounts:[],summary=E("accounts_usage_summary"),panel=E("accounts_usage_panel");if(!summary||!panel){return;}if(!list.length){summary.innerHTML="暂无账号额度数据";panel.innerHTML='<div class="ks_usage_empty">暂无账号额度数据。先导入账号，然后点击“一键刷新额度”。</div>';return;}var rows=[];for(var i=0;i<list.length;i++){var item=list[i]||{},email=item.email||"--",plan=item.planType||"--",statusHtml=item.usageError?'<span class="ks_usage_error">'+escapeHtml(item.usageError)+'</span>':'<span class="ks_usage_hint">'+((item.fiveHourUsedPercent===null||typeof item.fiveHourUsedPercent=="undefined")&&(item.oneWeekUsedPercent===null||typeof item.oneWeekUsedPercent=="undefined")?"待刷新":"已刷新")+"</span>";rows.push("<tr><td class=\"ks_usage_index\">"+(i+1)+"</td><td class=\"ks_usage_account\"><span class=\"ks_usage_email\">"+escapeHtml(email)+"</span><span class=\"ks_usage_planline\"><span class=\"ks_plan_badge\">"+escapeHtml(plan)+"</span></span></td><td>"+formatUsageCell(item.fiveHourUsedPercent,item.fiveHourResetAt)+"</td><td>"+formatUsageCell(item.oneWeekUsedPercent,item.oneWeekResetAt)+"</td><td class=\"ks_usage_status\">"+statusHtml+"</td></tr>");}summary.innerHTML="共 "+list.length+" 个账号";panel.innerHTML='<div class="ks_usage_panel_shell"><table class="ks_usage_table"><thead><tr><th class="ks_usage_index">#</th><th>账号</th><th>5h 已用</th><th>1周 已用</th><th class="ks_usage_status">状态</th></tr></thead><tbody>'+rows.join("")+"</tbody></table></div>";}
function renderImageStatus(r){var text=r.imageStatusText||"未拉取",kind=r.imageStatus||"missing",badgeClass="ks_badge_info";if(kind=="ready"){badgeClass="ks_badge_success";}else if(kind=="pulling"){badgeClass="ks_badge_warn";}else if(kind=="error"){badgeClass="ks_badge_error";}E("image_status").innerHTML='<span class="ks_badge '+badgeClass+'">'+escapeHtml(text)+'</span>';}
function scheduleRuntimeLogRefresh(ms){if(runtime_log_timer){clearTimeout(runtime_log_timer);runtime_log_timer=null;}if(ms>0&&pageIsVisible()){runtime_log_timer=setTimeout(function(){refresh_runtime_log(true);},ms);}}
function rememberPendingApiKeyValue(value){pending_api_key_value=String(value||"").replace(/^\s+|\s+$/g,"");}
function maybeUpdateApiKeyInput(value){var input=E("api_key_input"),nextValue=String(value||"");if(!input){return;}if(nextValue){pending_api_key_value="";}else if(pending_api_key_value){nextValue=pending_api_key_value;}if(document.activeElement===input){return;}if(input.value!==nextValue){input.value=nextValue;}}
function shouldShowCleanupConflictButton(r){return !!(r&&r.processConflict);}
function render_status(r){var t=[],kind="info",badge="检测中",cleanupButton=E("cleanup_conflict_button");if(r.processConflict){t.push(r.processConflictText||"检测到多个 codex-tools-proxyd 进程");kind="error";badge="异常";}else if(!r.dockrootInstalled){t.push("DockRoot 未检测到");kind="error";badge="异常";}else if(!r.containerExists){t.push("容器未创建");kind="warn";badge="未创建";}else if(!r.running){t.push("容器已创建但未运行");kind="warn";badge="未运行";}else{t.push("运行中");kind="success";badge="运行中";}if(r.dockrootInstalled&&r.dockrootVersion){t.push(r.dockrootVersion);}if(r.pid){t.push("PID: "+r.pid);}if(r.proxydPidCount&&r.proxydPidCount>1){t.push("Host PIDs: "+r.proxydPidCount);}if(cleanupButton){cleanupButton.style.display=shouldShowCleanupConflictButton(r)?"":"none";}setStatusBadge(kind,badge);E("status").innerHTML=t.join(" | ");renderImageStatus(r);E("local_base_url").innerHTML=r.localBaseUrl||"-";E("lan_base_url").innerHTML=r.lanBaseUrl||"-";E("data_dir").innerHTML=r.dataDir||E("data_dir").innerHTML;E("runtime_log_path").innerHTML=r.logPath||E("runtime_log_path").innerHTML;E("audit_log_path").innerHTML=r.auditLogPath||E("audit_log_path").innerHTML;E("error_log_path").innerHTML=r.errorLogPath||E("error_log_path").innerHTML;E("dockroot_bin").innerHTML=r.dockrootBin||E("dockroot_bin").innerHTML;E("accounts_present").innerHTML=r.accountsPresent?"已存在":"未导入";maybeUpdateApiKeyInput(r.apiKey||"");E("last_error").innerHTML=r.lastError||"无";E("last_import_at").innerHTML=formatLastImportText(r);E("codexproxyd_image_ref").value=r.imageRef||db_codexproxyd["codexproxyd_image_ref"]||E("codexproxyd_image_ref").value;E("codexproxyd_default_model").value="gpt-5.4";ensureSelectValue("codexproxyd_default_effort",r.defaultEffort||db_codexproxyd["codexproxyd_default_effort"]||E("codexproxyd_default_effort").value||"high");ensureSelectValue("codexproxyd_audit_log_level",r.auditLogLevel||db_codexproxyd["codexproxyd_audit_log_level"]||E("codexproxyd_audit_log_level").value||"basic");renderAccountsUsage(r.accountsUsage||[]);scheduleRuntimeLogRefresh(r.running?8e3:0);}
function toggleApiKey(){var i=E("api_key_input");i.type=i.type=="password"?"text":"password";}
function copyFromElement(id){var e=E(id),v=e.value||e.innerHTML||"";if(!v||v=="-"){return;}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(v);return;}var t=document.createElement("textarea");t.value=v;document.body.appendChild(t);t.select();document.execCommand("copy");document.body.removeChild(t);}
function copyLocalUrl(){copyFromElement("local_base_url");}
function copyLanUrl(){copyFromElement("lan_base_url");}
function onSaveSettings(){submitAction("save_settings");}
function onAction(name){submitAction(name);}
function actionNeedsLogPolling(name){return name!="save_settings"&&name!="import_accounts"&&name!="import_auth";}
function updateLoadingMessage(msg){$("#loading_block3").html(msg||"操作处理中...");}
function clearActionCloseTimer(){if(action_close_timer){clearTimeout(action_close_timer);action_close_timer=null;}}
function closeLoadingBarSoon(delay,onDone){clearActionCloseTimer();action_close_timer=setTimeout(function(){action_close_timer=null;if(onDone){onDone();}},delay||0);}
function handOffActionToStatusPolling(){updateLoadingMessage("操作日志暂时不可读，正在改用状态确认结果...");stopActionStatusRefresh();scheduleStatusPoll(3000);closeLoadingBarSoon(1200,function(){hideSSLoadingBar();});}
function stopActionStatusRefresh(){if(action_status_refresh_timer){clearInterval(action_status_refresh_timer);action_status_refresh_timer=null;}}
function startActionStatusRefresh(){stopActionStatusRefresh();get_run_status();refresh_runtime_log(true);action_status_refresh_timer=setInterval(function(){get_run_status();refresh_runtime_log(true);},3000);}
function scheduleActionLogPoll(ms){if(action_log_poll_timer){clearTimeout(action_log_poll_timer);action_log_poll_timer=null;}if(ms>0){action_log_poll_timer=setTimeout(function(){action_log_poll_timer=null;pollActionLog();},ms);}}
function inferActionCompletedFromStatus(actionName,result){if(!actionName){return false;}switch(actionName){case "pull_image":return !result.actionRunning&&!result.processConflict&&result.imageStatus=="ready";case "start":case "restart":case "regenerate_key":return !result.actionRunning&&!result.processConflict&&!!result.running;case "stop":return !result.actionRunning&&!result.processConflict&&result.containerExists&&!result.running;case "cleanup_conflict":return !result.actionRunning&&!result.processConflict;case "remove_container":return !result.actionRunning&&!result.processConflict&&!result.containerExists;default:return false;}}
function maybeFinishActionFromStatus(result){var state=result||status_cache||{},actionMatches=false,errorMessage="";if(!current_action_name){return false;}actionMatches=!state.actionName||state.actionName==current_action_name;if(state.processConflict){finishActionWithError(state.processConflictText||"检测到多个 codex-tools-proxyd 进程，请先排查运行状态。");return true;}if(inferActionCompletedFromStatus(current_action_name,state)){finishQuickAction(current_action_success_message||"操作成功");return true;}if(actionMatches&&state.actionStatus=="success"&&!state.actionRunning){finishQuickAction(current_action_success_message||state.actionMessage||"操作成功");return true;}if(actionMatches&&state.actionStatus=="error"){errorMessage=state.actionMessage||state.lastError||state.actionLastLine||"操作已结束，但状态未达到预期，请检查运行日志。";finishActionWithError(errorMessage);return true;}if(state.actionLogDone&&!state.actionRunning&&actionMatches){errorMessage=state.lastError||state.actionLastLine||"操作已结束，但状态未达到预期，请检查运行日志。";finishActionWithError(errorMessage);return true;}return false;}
function resetActionLogPolling(){scheduleActionLogPoll(0);stopActionStatusRefresh();action_log_poll_inflight=false;action_log_failures=0;action_log_started_at=0;current_action_name="";current_action_success_message="";}
function finishQuickAction(msg){resetActionLogPolling();clearActionCloseTimer();updateLoadingMessage(msg||"操作成功");closeLoadingBarSoon(800,function(){hideSSLoadingBar();get_dbus_data();get_run_status();refresh_runtime_log();refreshAuditLog();refreshErrorLog();});}
function finishActionWithError(msg){resetActionLogPolling();clearActionCloseTimer();updateLoadingMessage(msg||"操作失败");closeLoadingBarSoon(1500,function(){hideSSLoadingBar();get_dbus_data();get_run_status();refresh_runtime_log();refreshAuditLog();refreshErrorLog();});}
function normalizeActionResult(rawResult){var text=String(rawResult===null||typeof rawResult=="undefined"?"":rawResult).replace(/^\s+|\s+$/g,"");if(text.length>=2&&text.charAt(0)=='"'&&text.charAt(text.length-1)=='"'){text=text.substring(1,text.length-1).replace(/^\s+|\s+$/g,"");}return text;}
function isAcceptedActionReceipt(normalizedResult){return /^[0-9]+$/.test(normalizedResult);}
function buildFields(){return {"codexproxyd_enable":E("codexproxyd_enable").checked?"1":"0","codexproxyd_disk_path_selected":resolveDiskPathSelected(),"codexproxyd_data_dir_value":currentDataDirValue(),"codexproxyd_image_ref":currentImageRefValue(),"codexproxyd_api_key_value":E("api_key_input").value,"codexproxyd_default_model":E("codexproxyd_default_model").value,"codexproxyd_default_effort":E("codexproxyd_default_effort").value,"codexproxyd_audit_log_level":E("codexproxyd_audit_log_level").value,"codexproxyd_payload_kind":E("codexproxyd_payload_kind").value,"codexproxyd_payload_b64":"","codexproxyd_payload_b64_chunks":"0","codexproxyd_payload_text":"","codexproxyd_payload_text_chunks":"0","codexproxyd_usage_summary_b64":"","codexproxyd_usage_summary_b64_chunks":"0","codexproxyd_usage_summary_text":"","codexproxyd_usage_summary_text_chunks":"0","codexproxyd_request_id":""};}
function submitAction(actionName){var fields=buildFields(),successMessage="操作成功",importPayload="",id=parseInt(Math.random()*1e8),normalizedResult="";var expectedResult=String(id);fields["codexproxyd_action"]=actionName;if(!fields["codexproxyd_disk_path_selected"]&&actionName!="save_settings"){finishActionWithError("请先选择可用的磁盘挂载点。");return false;}clearActionCloseTimer();resetActionLogPolling();showSSLoadingBar();updateLoadingMessage("正在执行 "+actionName+"，请稍候...");fields["codexproxyd_request_id"]=expectedResult;if(actionName=="save_settings"){rememberPendingApiKeyValue(fields["codexproxyd_api_key_value"]);}if(actionName=="import_accounts"||actionName=="import_auth"){try{importPayload=prepareImportPayload(actionName);attachChunkedField(fields,"codexproxyd_payload_text",importPayload);attachChunkedField(fields,"codexproxyd_usage_summary_text",buildImportedUsageSummary(importPayload));successMessage=actionName=="import_accounts"?"导入 accounts.json 成功":"导入 auth.json 成功";}catch(error){hideSSLoadingBar();alert(error.message||error);return false;}}else if(actionName=="save_settings"){successMessage="保存设置成功";}else if(actionName=="refresh_usage"){successMessage="刷新额度成功";}else if(actionName=="cleanup_conflict"){successMessage="宿主机冲突清理完成";}var postData={id:id,method:"codexproxyd_action.sh",params:[actionName],fields:fields};$.ajax({url:"/_api/",cache:false,type:"POST",dataType:"json",data:JSON.stringify(postData),success:function(r){normalizedResult=normalizeActionResult(r.result);if(normalizedResult===expectedResult||isAcceptedActionReceipt(normalizedResult)){if(actionNeedsLogPolling(actionName)){startActionLogPolling(actionName,successMessage);}else{finishQuickAction(successMessage);}}else{finishActionWithError("提交失败: "+(normalizedResult||r.result));}},error:function(){finishActionWithError("提交失败，后台没有返回有效结果。");}});return false;}
function prepareImportPayload(actionName){var text=E("codexproxyd_payload_text").value;if(!text||!text.trim()){throw new Error("请先粘贴 accounts.json 或完整 auth.json 内容。");}return actionName=="import_accounts"?normalizeAccountsJson(text):convertAuthJsonToAccounts(text);}
function buildImportedUsageSummary(text){var payload=JSON.parse(text),accounts=$.isArray(payload.accounts)?payload.accounts:[],rows=[];for(var i=0;i<accounts.length;i++){rows.push(summaryFromImportedAccount(accounts[i]||{}));}return JSON.stringify(rows);}
function summaryFromImportedAccount(account){var usage=account.usage||{},fiveHour=usage.fiveHour||usage.five_hour||null,oneWeek=usage.oneWeek||usage.one_week||null;return {email:account.email||null,planType:account.planType||account.plan_type||usage.planType||usage.plan_type||null,fiveHourUsedPercent:fiveHour&&typeof fiveHour.usedPercent!="undefined"?fiveHour.usedPercent:(fiveHour&&typeof fiveHour.used_percent!="undefined"?fiveHour.used_percent:null),fiveHourResetAt:fiveHour&&typeof fiveHour.resetAt!="undefined"?fiveHour.resetAt:(fiveHour&&typeof fiveHour.reset_at!="undefined"?fiveHour.reset_at:null),oneWeekUsedPercent:oneWeek&&typeof oneWeek.usedPercent!="undefined"?oneWeek.usedPercent:(oneWeek&&typeof oneWeek.used_percent!="undefined"?oneWeek.used_percent:null),oneWeekResetAt:oneWeek&&typeof oneWeek.resetAt!="undefined"?oneWeek.resetAt:(oneWeek&&typeof oneWeek.reset_at!="undefined"?oneWeek.reset_at:null),usageError:account.usageError||account.usage_error||null};}
function normalizeAccountsJson(text){var p=JSON.parse(text);if(!p.version||!p.accounts||!p.settings){throw new Error("accounts.json 需要包含 version、accounts、settings。");}return JSON.stringify(p);}
function convertAuthJsonToAccounts(text){var authJson=JSON.parse(text),normalizedAuth=normalizeAuthJson(authJson),extracted=extractAuth(normalizedAuth),now=Math.floor(Date.now()/1000),account={id:makeUuid(),label:extracted.email||("Codex "+extracted.accountId.substring(0,8)),principalId:extracted.principalId,email:extracted.email||null,accountId:extracted.accountId,planType:extracted.planType||null,authJson:normalizedAuth,addedAt:now,updatedAt:now,usage:null,usageError:null,authRefreshBlocked:false,authRefreshError:null};return JSON.stringify({version:1,accounts:[account],settings:{}});}
function normalizeAuthJson(authJson){if(authJson.tokens){return authJson;}if(authJson.access_token&&authJson.id_token){var tokens={access_token:authJson.access_token,id_token:authJson.id_token};if(authJson.refresh_token){tokens.refresh_token=authJson.refresh_token;}if(authJson.account_id){tokens.account_id=authJson.account_id;}var normalized={auth_mode:authJson.auth_mode||"chatgpt",tokens:tokens};if(authJson.last_refresh){normalized.last_refresh=authJson.last_refresh;}return normalized;}throw new Error("auth.json 缺少可移植的 access_token / id_token。");}
function extractAuth(authJson){var tokens=authJson.tokens||{};if(!tokens.access_token){throw new Error("auth.json 缺少 access_token。");}if(!tokens.id_token){throw new Error("auth.json 缺少 id_token。");}var claims=decodeJwtPayload(tokens.id_token),authClaim=claims["https://api.openai.com/auth"]||{},accountId=tokens.account_id||authClaim.chatgpt_account_id;if(!accountId){throw new Error("无法从 auth.json 提取 chatgpt_account_id。");}var email=claims.email||null,principalId=normalizePrincipal(email)||normalizePrincipal(authClaim.chatgpt_user_id)||normalizePrincipal(authClaim.user_id)||normalizePrincipal(claims.sub)||accountId;return {accountId:accountId,email:email,planType:authClaim.chatgpt_plan_type||null,principalId:principalId};}
function normalizePrincipal(value){if(!value||typeof value!="string"){return "";}var trimmed=value.replace(/^\s+|\s+$/g,"");if(!trimmed){return "";}return trimmed.indexOf("@")>=0?trimmed.toLowerCase():trimmed;}
function decodeJwtPayload(token){var parts=token.split(".");if(parts.length<2){throw new Error("id_token 格式无效。");}var payload=parts[1].replace(/-/g,"+").replace(/_/g,"/");while(payload.length%4){payload+="=";}return JSON.parse(decodeURIComponent(escape(window.atob(payload))));}
function makeUuid(){if(window.crypto&&window.crypto.randomUUID){return window.crypto.randomUUID();}return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=="x"?r:(r&3|8);return v.toString(16);});}
function encodeUtf8Base64(text){return btoa(unescape(encodeURIComponent(text)));}
function startActionLogPolling(actionName,successMessage){resetActionLogPolling();current_action_name=actionName||"";current_action_success_message=successMessage||"操作成功";action_log_started_at=(new Date()).getTime();startActionStatusRefresh();pollActionLog();}
function actionPollingTimedOut(){return action_log_started_at>0&&((new Date()).getTime()-action_log_started_at)>45000;}
function pollActionLog(){if(action_log_poll_inflight){return;}if(actionPollingTimedOut()){handOffActionToStatusPolling();return;}action_log_poll_inflight=true;var id=parseInt(Math.random()*1e8),postData={id:id,method:"codexproxyd_log.sh",params:["action"],fields:{"codexproxyd_log_kind":"action"}};$.ajax({type:"POST",cache:false,url:"/_api/",data:JSON.stringify(postData),dataType:"json",success:function(r){action_log_poll_inflight=false;action_log_failures=0;var result=typeof r.result=="string"?r.result:"",clean=result.replace("XU6J03M6"," ").replace(/^\s+|\s+$/g,"");updateLoadingMessage(clean||"正在等待操作日志输出...");refresh_runtime_log(true);if(result.indexOf("XU6J03M6")!=-1){updateLoadingMessage("操作日志已结束，正在确认最终状态...");get_run_status();return;}$("#loading_block3").scrollTop($("#loading_block3").prop("scrollHeight"));scheduleActionLogPoll(1000);},error:function(){action_log_poll_inflight=false;action_log_failures++;if(action_log_failures>=5||actionPollingTimedOut()){handOffActionToStatusPolling();return;}scheduleActionLogPoll(1000);}});}
function refresh_runtime_log(isSilent){refreshLog("runtime","runtime_log","运行日志读取失败",isSilent);}
function refreshAuditLog(isSilent){refreshLog("audit","audit_log","请求审计日志读取失败",isSilent);}
function refreshErrorLog(isSilent){refreshLog("error","error_log","错误日志读取失败",isSilent);}
function refreshLog(kind,targetId,failureText,isSilent){if(log_request_inflight[kind]){return;}log_request_inflight[kind]=true;var id=parseInt(Math.random()*1e8),postData={id:id,method:"codexproxyd_log.sh",params:[kind],fields:{"codexproxyd_log_kind":kind}};$.ajax({type:"POST",cache:false,url:"/_api/",data:JSON.stringify(postData),dataType:"json",success:function(r){log_request_inflight[kind]=false;E(targetId).value=typeof r.result=="string"?r.result:"";if(kind=="runtime"){scheduleRuntimeLogRefresh(status_cache.running?8e3:0);}},error:function(){log_request_inflight[kind]=false;if(!isSilent){E(targetId).value=failureText;}if(kind=="runtime"){scheduleRuntimeLogRefresh(status_cache.running?8e3:0);}}});}
function hideSSLoadingBar(){if(E("Loading")){E("Loading").style.visibility="hidden";E("Loading").style.display="none";}if(E("LoadingBar")){E("LoadingBar").style.visibility="hidden";E("LoadingBar").style.display="none";}}
function showSSLoadingBar(){if(window.scrollTo){window.scrollTo(0,0);}winW_H();var blockmarginTop,blockmarginLeft;if(window.innerWidth)winWidth=window.innerWidth;else if((document.body)&&(document.body.clientWidth))winWidth=document.body.clientWidth;if(window.innerHeight)winHeight=window.innerHeight;else if((document.body)&&(document.body.clientHeight))winHeight=document.body.clientHeight;if(document.documentElement&&document.documentElement.clientHeight&&document.documentElement.clientWidth){winHeight=document.documentElement.clientHeight;winWidth=document.documentElement.clientWidth;}if(winWidth>1050){winPadding=(winWidth-1050)/2;winWidth=1105;blockmarginLeft=(winWidth*.3)+winPadding-150;}else{blockmarginLeft=(winWidth)*.3+document.body.scrollLeft-160;}if(winHeight>660)winHeight=660;blockmarginTop=winHeight*.5;E("loadingBarBlock").style.marginTop=blockmarginTop+"px";E("loadingBarBlock").style.marginLeft=blockmarginLeft+"px";E("loadingBarBlock").style.width=770+"px";if(E("Loading")){E("Loading").style.display="none";E("Loading").style.visibility="hidden";}if(E("LoadingBar")){E("LoadingBar").style.display="block";E("LoadingBar").style.width=winW+"px";E("LoadingBar").style.height=winH+"px";E("LoadingBar").style.visibility="visible";}}
</script></head>
<body id="app" skin="ASUSWRT" onload="init();"><div id="TopBanner"></div><div id="Loading" class="popup_bg"></div><div id="LoadingBar" class="popup_bar_bg"><table cellpadding="5" cellspacing="0" id="loadingBarBlock" class="loadingBarBlock" align="center"><tr><td height="100"><div id="loading_block3">数据提交中，请稍候...</div></td></tr></table></div>
<table class="content" align="center" cellpadding="0" cellspacing="0"><tr><td width="17">&nbsp;</td><td valign="top" width="202"><div id="mainMenu"></div><div id="subMenu"></div></td><td valign="top"><div id="tabMenu" class="submenuBlock"></div><table width="98%" border="0" align="left" cellpadding="0" cellspacing="0"><tr><td align="left" valign="top"><table width="760px" border="0" cellpadding="5" cellspacing="0" bordercolor="#6b8fa3" class="FormTitle" id="FormTitle" style="border:0px solid transparent;"><tr><td bgcolor="#4D595D" colspan="3" valign="top" style="border-radius:8px"><div>&nbsp;</div><div class="formfonttitle">软件中心 - codexproxyd</div><div style="float:right;width:15px;height:25px;margin-top:-20px"><img id="return_btn" onclick="reload_Soft_Center();" align="right" style="cursor:pointer;position:absolute;margin-left:-30px;margin-top:-25px;" title="返回软件中心" src="/images/backprev.png" onMouseOver="this.src='/images/backprevclick.png'" onMouseOut="this.src='/images/backprev.png'"></img></div><div style="margin:30px 0 10px 5px;" class="splitLine"></div><div class="SimpleNote"><li>这个插件管理运行在 DockRoot 中的 codex-tools-proxyd 容器。</li><li>请先安装 DockRoot，并准备一个 ext4 U 盘或硬盘作为容器和数据存储。</li></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">状态概览</td></tr></thead><tr><th>运行状态</th><td><span id="status_badge" class="ks_badge ks_badge_info">检测中</span><span id="status" class="ks_status_detail">获取中...</span></td></tr><tr><th>镜像状态</th><td><span id="image_status"><span class="ks_badge ks_badge_info">检测中</span></span></td></tr><tr><th>本机 URL</th><td class="ks_info"><div class="ks_inline_row"><span id="local_base_url">-</span><input class="button_gen" style="width:60px" type="button" value="复制" onclick="copyLocalUrl();" /></div></td></tr><tr><th>局域网 URL</th><td class="ks_info"><div class="ks_inline_row"><span id="lan_base_url">-</span><input class="button_gen" style="width:60px" type="button" value="复制" onclick="copyLanUrl();" /></div></td></tr><tr><th>API Key</th><td><input id="api_key_input" class="input_ss_table" type="password" value="" placeholder="留空则保持当前 key 不变" /><input class="button_gen" style="width:90px" type="button" value="显示/隐藏" onclick="toggleApiKey();" /><input class="button_gen" style="width:60px" type="button" value="复制" onclick="copyFromElement('api_key_input');" /></td></tr><tr><th>accounts.json</th><td><span id="accounts_present">-</span></td></tr><tr><th>最近导入</th><td><span id="last_import_at">-</span></td></tr><tr><th>最近错误</th><td><span id="last_error">-</span></td></tr></table>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">Default Proxy Settings</td></tr></thead><tr><th>Default Model</th><td><select id="codexproxyd_default_model" class="input_option"><option value="gpt-5.4" selected="selected">gpt-5.4</option></select></td></tr><tr><th>Default Effort</th><td><select id="codexproxyd_default_effort" class="input_option"><option value="low">low</option><option value="medium">medium</option><option value="high" selected="selected">high</option><option value="xhigh">xhigh</option></select></td></tr><tr><th>Audit Log Level</th><td><select id="codexproxyd_audit_log_level" class="input_option"><option value="off">off</option><option value="basic" selected="selected">basic</option><option value="debug">debug</option></select></td></tr></table>
<div style="margin:20px 0 10px 5px;" class="splitLine"></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">运行配置</td></tr></thead><tr><th>开机自启</th><td><div style="display:table-cell;float:left;"><label for="codexproxyd_enable"><input id="codexproxyd_enable" class="switch" type="checkbox" style="display:none;"><div class="switch_container"><div class="switch_bar"></div><div class="switch_circle transition_style"><div></div></div></div></label></div></td></tr><tr><th>磁盘挂载点</th><td><select name="codexproxyd_disk_path_selected" id="codexproxyd_disk_path_selected" class="input_option" onchange="refresh_paths();"></select></td></tr><tr><th>镜像地址</th><td><input id="codexproxyd_image_ref" type="text" class="input_ss_table" style="width:96%;" value="" placeholder="例如: ghcr.io/example/codex-tools-proxyd:latest" /></td></tr><tr><th>DockRoot 路径</th><td class="ks_info"><code id="dockroot_bin">-</code></td></tr><tr><th>数据目录</th><td class="ks_info"><code id="data_dir">-</code></td></tr><tr><th>运行日志</th><td class="ks_info"><code id="runtime_log_path">-</code></td></tr><tr><th>Audit Log</th><td class="ks_info"><code id="audit_log_path">-</code></td></tr><tr><th>Error Log</th><td class="ks_info"><code id="error_log_path">-</code></td></tr><tr><th>操作</th><td><input class="button_gen" type="button" value="保存设置" onclick="onSaveSettings();" /><input class="button_gen" type="button" value="拉取/更新镜像" onclick="onAction('pull_image');" /><input class="button_gen" type="button" value="启动" onclick="onAction('start');" /><input class="button_gen" type="button" value="停止" onclick="onAction('stop');" /><input class="button_gen" type="button" value="重启" onclick="onAction('restart');" /><input id="cleanup_conflict_button" class="button_gen" type="button" value="清理宿主机冲突" onclick="onAction('cleanup_conflict');" style="display:none;" /><input class="button_gen" type="button" value="刷新 Key" onclick="onAction('regenerate_key');" /><input class="button_gen" type="button" value="删除容器" onclick="onAction('remove_container');" /></td></tr></table>
<div style="margin:20px 0 10px 5px;" class="splitLine"></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">账号额度</td></tr></thead><tr><th>刷新</th><td><div class="ks_usage_actions"><input class="button_gen" type="button" value="一键刷新额度" onclick="onAction('refresh_usage');" /><span id="accounts_usage_summary" class="ks_usage_meta">暂无账号额度数据</span></div></td></tr><tr><th>账号列表</th><td><div id="accounts_usage_panel" class="ks_usage_empty">暂无账号额度数据。先导入账号，然后点击“一键刷新额度”。</div></td></tr></table>
<div style="margin:20px 0 10px 5px;" class="splitLine"></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">账号导入</td></tr></thead><tr><th>导入模式</th><td><select id="codexproxyd_payload_kind" class="input_option"><option value="accounts_json">accounts.json</option><option value="auth_json">auth.json</option></select></td></tr><tr><th>粘贴内容</th><td><textarea id="codexproxyd_payload_text" class="ks_payload" spellcheck="false" placeholder="在这里粘贴 accounts.json 或完整 auth.json"></textarea></td></tr><tr><th>导入说明</th><td class="ks_info"><li>选择 <code>accounts.json</code> 时会直接校验并写入数据目录。</li><li>选择 <code>auth.json</code> 时，页面会先转换成单账号 <code>accounts.json</code>，再提交给插件保存。</li></td></tr><tr><th>导入操作</th><td><input class="button_gen" type="button" value="导入 accounts.json" onclick="onAction('import_accounts');" /><input class="button_gen" type="button" value="导入 auth.json" onclick="onAction('import_auth');" /></td></tr></table>
<div style="margin:20px 0 10px 5px;" class="splitLine"></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">运行日志</td></tr></thead><tr><th>日志尾部</th><td><textarea id="runtime_log" class="ks_runtime_log" readonly="readonly" spellcheck="false"></textarea></td></tr><tr><th>日志操作</th><td><input class="button_gen" type="button" value="刷新运行日志" onclick="refresh_runtime_log();" /></td></tr></table>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">Request Audit Log</td></tr></thead><tr><th>Recent Entries</th><td><textarea id="audit_log" class="ks_runtime_log" readonly="readonly" spellcheck="false"></textarea></td></tr><tr><th>Actions</th><td><input class="button_gen" type="button" value="Refresh Audit Log" onclick="refreshAuditLog();" /></td></tr></table>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">Error Log</td></tr></thead><tr><th>Recent Errors</th><td><textarea id="error_log" class="ks_runtime_log" readonly="readonly" spellcheck="false"></textarea></td></tr><tr><th>Actions</th><td><input class="button_gen" type="button" value="Refresh Error Log" onclick="refreshErrorLog();" /></td></tr></table>
<div style="margin:30px 0 10px 5px;" class="splitLine"></div></td></tr></table></td></tr></table></td><td width="10" align="center" valign="top"></td></tr></table><div id="footer"></div></body></html>
