<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta HTTP-EQUIV="Pragma" CONTENT="no-cache"/><meta HTTP-EQUIV="Expires" CONTENT="-1"/>
<link rel="shortcut icon" href="images/favicon.png"/><link rel="icon" href="images/favicon.png"/>
<title>软件中心 - codexproxyd</title>
<link rel="stylesheet" type="text/css" href="index_style.css"/><link rel="stylesheet" type="text/css" href="form_style.css"/><link rel="stylesheet" type="text/css" href="usp_style.css"/><link rel="stylesheet" type="text/css" href="css/element.css"><link rel="stylesheet" type="text/css" href="/device-map/device-map.css"><link rel="stylesheet" type="text/css" href="/res/softcenter.css">
<script type="text/javascript" src="/js/jquery.js"></script><script type="text/javascript" src="/state.js"></script><script type="text/javascript" src="/popup.js"></script><script type="text/javascript" src="/validator.js"></script><script type="text/javascript" src="/general.js"></script><script type="text/javascript" src="/res/softcenter.js"></script>
<style>
#loading_block3{margin:10px auto;width:85%;font-size:12pt;white-space:pre-line}.ks_info{line-height:24px}.ks_info code{font-family:Consolas,monospace;background:rgba(0,0,0,.18);padding:2px 6px;border-radius:4px}textarea.ks_payload,textarea.ks_runtime_log{width:98%;background:rgba(0,0,0,.2);color:#fff;border:1px solid rgba(255,255,255,.2);padding:10px;font-family:Consolas,monospace;resize:vertical}textarea.ks_payload{min-height:180px}textarea.ks_runtime_log{min-height:220px}input.readonly_field{width:320px!important}input[type=button]:focus{outline:none}.ks_badge{display:inline-block;min-width:72px;padding:2px 10px;margin-right:8px;border-radius:999px;font-size:12px;font-weight:bold;text-align:center;color:#fff}.ks_badge_success{background:#2e8b57}.ks_badge_warn{background:#d08a00}.ks_badge_error{background:#b94a48}.ks_badge_info{background:#5b7fa3}.ks_status_detail{display:inline-block;vertical-align:middle}.ks_inline_row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.ks_inline_row .button_gen{min-width:60px}
</style>
<script>
var db_codexproxyd={},status_cache={},status_poll_timer=null,runtime_log_timer=null;
function init(){show_menu(menu_hook);set_skin();get_dbus_data();get_disks();get_run_status();refresh_runtime_log();refreshAuditLog();refreshErrorLog();}
function set_skin(){var s='<% nvram_get("sc_skin"); %>';if(s){$("#app").attr("skin",s);}}
function menu_hook(){tabtitle[tabtitle.length-1]=new Array("","codexproxyd","__INHERIT__");tablink[tablink.length-1]=new Array("","Module_codexproxyd.asp","NULL");}
function reload_Soft_Center(){location.href="/Module_Softcenter.asp";}
function get_dbus_data(){$.ajax({type:"GET",url:"/_api/codexproxyd",dataType:"json",async:false,success:function(d){db_codexproxyd=d.result[0]||{};conf_to_obj();}});}
function conf_to_obj(){E("codexproxyd_enable").checked=db_codexproxyd["codexproxyd_enable"]=="1";E("codexproxyd_disk_path_selected").value=db_codexproxyd["codexproxyd_disk_path_selected"]||"";E("codexproxyd_image_ref").value=db_codexproxyd["codexproxyd_image_ref"]||"";ensureSelectValue("codexproxyd_default_model",db_codexproxyd["codexproxyd_default_model"]||"gpt-5.4");ensureSelectValue("codexproxyd_default_effort",db_codexproxyd["codexproxyd_default_effort"]||"high");ensureSelectValue("codexproxyd_audit_log_level",db_codexproxyd["codexproxyd_audit_log_level"]||"basic");refresh_paths();}
function ensureSelectValue(id,value){var s=E(id),v=value||"";if(!s){return;}for(var i=0;i<s.options.length;i++){if(s.options[i].value==v){s.value=v;return;}}if(v){var o=document.createElement("option");o.value=v;o.text=v+" (custom)";s.appendChild(o);s.value=v;}}
function formatDiskSize(bytes){var u=["B","KB","MB","GB","TB"],s=bytes,i=0;while(s>=1024&&i<u.length-1){s/=1024;i++;}return s.toFixed(2)+" "+u[i];}
function get_disks(){require(['/require/modules/diskList.js'],function(diskList){var l=diskList.list();for(var i=0;i<l.length;++i){for(var j=0;j<l[i].partition.length;++j){var p=l[i].partition[j],m='/tmp/mnt/'+p.partName,t=m+"|"+p.format+"|"+formatDiskSize(p.size);$("#codexproxyd_disk_path_selected").append("<option value='"+m+"'>"+t+"</option>");}}if(db_codexproxyd["codexproxyd_disk_path_selected"]){E("codexproxyd_disk_path_selected").value=db_codexproxyd["codexproxyd_disk_path_selected"];}refresh_paths();});}
function refresh_paths(){var d=E("codexproxyd_disk_path_selected").value||"";E("data_dir").innerHTML=d?d+"/codex-proxyd-data":"-";E("dockroot_bin").innerHTML=d?d+"/DockRootBin/DockRoot":"-";E("runtime_log_path").innerHTML=d?d+"/DockRootData/codexproxyd/ruri.log":"-";E("audit_log_path").innerHTML=d?d+"/codex-proxyd-data/logs/access.jsonl":"-";E("error_log_path").innerHTML=d?d+"/codex-proxyd-data/logs/error.jsonl":"-";}
function get_run_status(){var id=parseInt(Math.random()*1e8),postData={id:id,method:"codexproxyd_status.sh",params:[],fields:""};$.ajax({type:"POST",cache:false,url:"/_api/",data:JSON.stringify(postData),dataType:"json",success:function(r){var result=JSON.parse(r.result);status_cache=result||{};render_status(result||{});if(status_poll_timer){clearTimeout(status_poll_timer);}status_poll_timer=setTimeout(get_run_status,1e4);},error:function(){setStatusBadge("error","异常");E("status").innerHTML="状态读取失败";scheduleRuntimeLogRefresh(0);if(status_poll_timer){clearTimeout(status_poll_timer);}status_poll_timer=setTimeout(get_run_status,5e3);}});}
function setStatusBadge(kind,text){var b=E("status_badge");b.className="ks_badge ks_badge_"+kind;b.innerHTML=text;}
function formatLastImportText(r){if(r.lastImportAt){return r.lastImportAt;}if(r.accountsPresent){return "已存在（外部导入）";}return "未导入";}
function scheduleRuntimeLogRefresh(ms){if(runtime_log_timer){clearTimeout(runtime_log_timer);runtime_log_timer=null;}if(ms>0){runtime_log_timer=setTimeout(function(){refresh_runtime_log(true);refreshAuditLog(true);refreshErrorLog(true);},ms);}}
function render_status(r){var t=[],kind="info",badge="检测中";if(!r.dockrootInstalled){t.push("DockRoot 未检测到");kind="error";badge="异常";}else if(!r.containerExists){t.push("容器未创建");kind="warn";badge="未创建";}else if(!r.running){t.push("容器已创建但未运行");kind="warn";badge="未运行";}else{t.push("运行中");kind="success";badge="运行中";}if(r.dockrootInstalled&&r.dockrootVersion){t.push(r.dockrootVersion);}if(r.pid){t.push("PID: "+r.pid);}setStatusBadge(kind,badge);E("status").innerHTML=t.join(" | ");E("local_base_url").innerHTML=r.localBaseUrl||"-";E("lan_base_url").innerHTML=r.lanBaseUrl||"-";E("data_dir").innerHTML=r.dataDir||E("data_dir").innerHTML;E("runtime_log_path").innerHTML=r.logPath||E("runtime_log_path").innerHTML;E("audit_log_path").innerHTML=r.auditLogPath||E("audit_log_path").innerHTML;E("error_log_path").innerHTML=r.errorLogPath||E("error_log_path").innerHTML;E("dockroot_bin").innerHTML=r.dockrootBin||E("dockroot_bin").innerHTML;E("accounts_present").innerHTML=r.accountsPresent?"已存在":"未导入";E("api_key_input").value=r.apiKey||"";E("last_error").innerHTML=r.lastError||"无";E("last_import_at").innerHTML=formatLastImportText(r);E("codexproxyd_image_ref").value=db_codexproxyd["codexproxyd_image_ref"]||E("codexproxyd_image_ref").value;ensureSelectValue("codexproxyd_default_model",r.defaultModel||db_codexproxyd["codexproxyd_default_model"]||E("codexproxyd_default_model").value||"gpt-5.4");ensureSelectValue("codexproxyd_default_effort",r.defaultEffort||db_codexproxyd["codexproxyd_default_effort"]||E("codexproxyd_default_effort").value||"high");ensureSelectValue("codexproxyd_audit_log_level",r.auditLogLevel||db_codexproxyd["codexproxyd_audit_log_level"]||E("codexproxyd_audit_log_level").value||"basic");scheduleRuntimeLogRefresh(r.running?5e3:0);}
function toggleApiKey(){var i=E("api_key_input");i.type=i.type=="password"?"text":"password";}
function copyFromElement(id){var e=E(id),v=e.value||e.innerHTML||"";if(!v||v=="-"){return;}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(v);return;}var t=document.createElement("textarea");t.value=v;document.body.appendChild(t);t.select();document.execCommand("copy");document.body.removeChild(t);}
function copyLocalUrl(){copyFromElement("local_base_url");}
function copyLanUrl(){copyFromElement("lan_base_url");}
function onSaveSettings(){submitAction("save_settings");}
function onAction(name){submitAction(name);}
function actionNeedsLogPolling(name){return name!="save_settings";}
function finishQuickAction(msg){$("#loading_block3").html(msg||"操作成功");setTimeout(function(){hideSSLoadingBar();get_dbus_data();get_run_status();refresh_runtime_log();refreshAuditLog();refreshErrorLog();},800);}
function buildFields(){return {"codexproxyd_enable":E("codexproxyd_enable").checked?"1":"0","codexproxyd_disk_path_selected":E("codexproxyd_disk_path_selected").value,"codexproxyd_image_ref":E("codexproxyd_image_ref").value,"codexproxyd_default_model":E("codexproxyd_default_model").value,"codexproxyd_default_effort":E("codexproxyd_default_effort").value,"codexproxyd_audit_log_level":E("codexproxyd_audit_log_level").value,"codexproxyd_payload_kind":E("codexproxyd_payload_kind").value,"codexproxyd_payload_b64":""};}
function submitAction(actionName){var fields=buildFields();fields["codexproxyd_action"]=actionName;if(actionName=="import_accounts"||actionName=="import_auth"){try{fields["codexproxyd_payload_b64"]=encodeUtf8Base64(prepareImportPayload(actionName));}catch(error){alert(error.message||error);return false;}}showSSLoadingBar();$("#loading_block3").html("正在执行 "+actionName+"，请稍候...");var id=parseInt(Math.random()*1e8),postData={id:id,method:"codexproxyd_action.sh",params:[],fields:fields};$.ajax({url:"/_api/",cache:false,type:"POST",dataType:"json",data:JSON.stringify(postData),success:function(r){if(r.result==id){if(actionNeedsLogPolling(actionName)){pollActionLog();}else{finishQuickAction("保存设置成功");}}else{$("#loading_block3").html("提交失败: "+r.result);}},error:function(){$("#loading_block3").html("提交失败，后台没有返回有效结果。");}});return false;}
function prepareImportPayload(actionName){var text=E("codexproxyd_payload_text").value;if(!text||!text.trim()){throw new Error("请先粘贴 accounts.json 或完整 auth.json 内容。");}return actionName=="import_accounts"?normalizeAccountsJson(text):convertAuthJsonToAccounts(text);}
function normalizeAccountsJson(text){var p=JSON.parse(text);if(!p.version||!p.accounts||!p.settings){throw new Error("accounts.json 需要包含 version、accounts、settings。");}return JSON.stringify(p,null,2);}
function convertAuthJsonToAccounts(text){var authJson=JSON.parse(text),normalizedAuth=normalizeAuthJson(authJson),extracted=extractAuth(normalizedAuth),now=Math.floor(Date.now()/1000),account={id:makeUuid(),label:extracted.email||("Codex "+extracted.accountId.substring(0,8)),principalId:extracted.principalId,email:extracted.email||null,accountId:extracted.accountId,planType:extracted.planType||null,authJson:normalizedAuth,addedAt:now,updatedAt:now,usage:null,usageError:null,authRefreshBlocked:false,authRefreshError:null};return JSON.stringify({version:1,accounts:[account],settings:{}},null,2);}
function normalizeAuthJson(authJson){if(authJson.tokens){return authJson;}if(authJson.access_token&&authJson.id_token){var tokens={access_token:authJson.access_token,id_token:authJson.id_token};if(authJson.refresh_token){tokens.refresh_token=authJson.refresh_token;}if(authJson.account_id){tokens.account_id=authJson.account_id;}var normalized={auth_mode:authJson.auth_mode||"chatgpt",tokens:tokens};if(authJson.last_refresh){normalized.last_refresh=authJson.last_refresh;}return normalized;}throw new Error("auth.json 缺少可移植的 access_token / id_token。");}
function extractAuth(authJson){var tokens=authJson.tokens||{};if(!tokens.access_token){throw new Error("auth.json 缺少 access_token。");}if(!tokens.id_token){throw new Error("auth.json 缺少 id_token。");}var claims=decodeJwtPayload(tokens.id_token),authClaim=claims["https://api.openai.com/auth"]||{},accountId=tokens.account_id||authClaim.chatgpt_account_id;if(!accountId){throw new Error("无法从 auth.json 提取 chatgpt_account_id。");}var email=claims.email||null,principalId=normalizePrincipal(email)||normalizePrincipal(authClaim.chatgpt_user_id)||normalizePrincipal(authClaim.user_id)||normalizePrincipal(claims.sub)||accountId;return {accountId:accountId,email:email,planType:authClaim.chatgpt_plan_type||null,principalId:principalId};}
function normalizePrincipal(value){if(!value||typeof value!="string"){return "";}var trimmed=value.replace(/^\s+|\s+$/g,"");if(!trimmed){return "";}return trimmed.indexOf("@")>=0?trimmed.toLowerCase():trimmed;}
function decodeJwtPayload(token){var parts=token.split(".");if(parts.length<2){throw new Error("id_token 格式无效。");}var payload=parts[1].replace(/-/g,"+").replace(/_/g,"/");while(payload.length%4){payload+="=";}return JSON.parse(decodeURIComponent(escape(window.atob(payload))));}
function makeUuid(){if(window.crypto&&window.crypto.randomUUID){return window.crypto.randomUUID();}return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=="x"?r:(r&3|8);return v.toString(16);});}
function encodeUtf8Base64(text){return btoa(unescape(encodeURIComponent(text)));}
function pollActionLog(){$.ajax({url:'/tmp/upload/codexproxyd_log.txt',type:'GET',cache:false,dataType:'text',success:function(r){var clean=r.replace("XU6J03M6"," ");$("#loading_block3").html(clean);if(r.search("XU6J03M6")!=-1){setTimeout(function(){hideSSLoadingBar();get_run_status();refresh_runtime_log();refreshAuditLog();refreshErrorLog();},1200);}else{$("#loading_block3").scrollTop($("#loading_block3").prop("scrollHeight"));setTimeout("pollActionLog();",1000);}},error:function(){setTimeout("pollActionLog();",1000);}});}
function refresh_runtime_log(isSilent){refreshLog("runtime","runtime_log","运行日志读取失败",isSilent);}
function refreshAuditLog(isSilent){refreshLog("audit","audit_log","请求审计日志读取失败",isSilent);}
function refreshErrorLog(isSilent){refreshLog("error","error_log","错误日志读取失败",isSilent);}
function refreshLog(kind,targetId,failureText,isSilent){var id=parseInt(Math.random()*1e8),postData={id:id,method:"codexproxyd_log.sh",params:[],fields:{"codexproxyd_log_kind":kind}};$.ajax({type:"POST",cache:false,url:"/_api/",data:JSON.stringify(postData),dataType:"json",success:function(r){E(targetId).value=r.result||"";if(kind=="runtime"){scheduleRuntimeLogRefresh(status_cache.running?5e3:0);}},error:function(){if(!isSilent){E(targetId).value=failureText;}if(kind=="runtime"){scheduleRuntimeLogRefresh(status_cache.running?5e3:0);}}});}
function hideSSLoadingBar(){E("LoadingBar").style.visibility="hidden";}
function showSSLoadingBar(){if(window.scrollTo){window.scrollTo(0,0);}winW_H();var blockmarginTop,blockmarginLeft;if(window.innerWidth)winWidth=window.innerWidth;else if((document.body)&&(document.body.clientWidth))winWidth=document.body.clientWidth;if(window.innerHeight)winHeight=window.innerHeight;else if((document.body)&&(document.body.clientHeight))winHeight=document.body.clientHeight;if(document.documentElement&&document.documentElement.clientHeight&&document.documentElement.clientWidth){winHeight=document.documentElement.clientHeight;winWidth=document.documentElement.clientWidth;}if(winWidth>1050){winPadding=(winWidth-1050)/2;winWidth=1105;blockmarginLeft=(winWidth*.3)+winPadding-150;}else{blockmarginLeft=(winWidth)*.3+document.body.scrollLeft-160;}if(winHeight>660)winHeight=660;blockmarginTop=winHeight*.5;E("loadingBarBlock").style.marginTop=blockmarginTop+"px";E("loadingBarBlock").style.marginLeft=blockmarginLeft+"px";E("loadingBarBlock").style.width=770+"px";E("LoadingBar").style.width=winW+"px";E("LoadingBar").style.height=winH+"px";E("LoadingBar").style.visibility="visible";}
</script></head>
<body id="app" skin="ASUSWRT" onload="init();"><div id="TopBanner"></div><div id="Loading" class="popup_bg"></div><div id="LoadingBar" class="popup_bar_bg"><table cellpadding="5" cellspacing="0" id="loadingBarBlock" class="loadingBarBlock" align="center"><tr><td height="100"><div id="loading_block3">数据提交中，请稍候...</div></td></tr></table></div>
<table class="content" align="center" cellpadding="0" cellspacing="0"><tr><td width="17">&nbsp;</td><td valign="top" width="202"><div id="mainMenu"></div><div id="subMenu"></div></td><td valign="top"><div id="tabMenu" class="submenuBlock"></div><table width="98%" border="0" align="left" cellpadding="0" cellspacing="0"><tr><td align="left" valign="top"><table width="760px" border="0" cellpadding="5" cellspacing="0" bordercolor="#6b8fa3" class="FormTitle" id="FormTitle" style="border:0px solid transparent;"><tr><td bgcolor="#4D595D" colspan="3" valign="top" style="border-radius:8px"><div>&nbsp;</div><div class="formfonttitle">软件中心 - codexproxyd</div><div style="float:right;width:15px;height:25px;margin-top:-20px"><img id="return_btn" onclick="reload_Soft_Center();" align="right" style="cursor:pointer;position:absolute;margin-left:-30px;margin-top:-25px;" title="返回软件中心" src="/images/backprev.png" onMouseOver="this.src='/images/backprevclick.png'" onMouseOut="this.src='/images/backprev.png'"></img></div><div style="margin:30px 0 10px 5px;" class="splitLine"></div><div class="SimpleNote"><li>这个插件管理运行在 DockRoot 中的 codex-tools-proxyd 容器。</li><li>请先安装 DockRoot，并准备一个 ext4 U 盘或硬盘作为容器和数据存储。</li></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">状态概览</td></tr></thead><tr><th>运行状态</th><td><span id="status_badge" class="ks_badge ks_badge_info">检测中</span><span id="status" class="ks_status_detail">获取中...</span></td></tr><tr><th>本机 URL</th><td class="ks_info"><div class="ks_inline_row"><span id="local_base_url">-</span><input class="button_gen" style="width:60px" type="button" value="复制" onclick="copyLocalUrl();" /></div></td></tr><tr><th>局域网 URL</th><td class="ks_info"><div class="ks_inline_row"><span id="lan_base_url">-</span><input class="button_gen" style="width:60px" type="button" value="复制" onclick="copyLanUrl();" /></div></td></tr><tr><th>API Key</th><td><input id="api_key_input" class="input_ss_table readonly_field" type="password" readonly="readonly" value="" /><input class="button_gen" style="width:90px" type="button" value="显示/隐藏" onclick="toggleApiKey();" /><input class="button_gen" style="width:60px" type="button" value="复制" onclick="copyFromElement('api_key_input');" /></td></tr><tr><th>accounts.json</th><td><span id="accounts_present">-</span></td></tr><tr><th>最近导入</th><td><span id="last_import_at">-</span></td></tr><tr><th>最近错误</th><td><span id="last_error">-</span></td></tr></table>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">Default Proxy Settings</td></tr></thead><tr><th>Default Model</th><td><select id="codexproxyd_default_model" class="input_option"><option value="gpt-5.4" selected="selected">gpt-5.4</option><option value="gpt-5">gpt-5</option><option value="gpt-5-mini">gpt-5-mini</option><option value="gpt-5-codex">gpt-5-codex</option><option value="gpt-5-codex-mini">gpt-5-codex-mini</option><option value="gpt-5.1-codex">gpt-5.1-codex</option><option value="gpt-5.1-codex-mini">gpt-5.1-codex-mini</option><option value="gpt-5.1-codex-max">gpt-5.1-codex-max</option><option value="gpt-5.2-codex">gpt-5.2-codex</option><option value="gpt-5.3-codex">gpt-5.3-codex</option><option value="gpt-5.3-codex-spark">gpt-5.3-codex-spark</option></select></td></tr><tr><th>Default Effort</th><td><select id="codexproxyd_default_effort" class="input_option"><option value="minimal">minimal</option><option value="low">low</option><option value="medium">medium</option><option value="high" selected="selected">high</option></select></td></tr><tr><th>Audit Log Level</th><td><select id="codexproxyd_audit_log_level" class="input_option"><option value="off">off</option><option value="basic" selected="selected">basic</option><option value="debug">debug</option></select></td></tr></table>
<div style="margin:20px 0 10px 5px;" class="splitLine"></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">运行配置</td></tr></thead><tr><th>开机自启</th><td><div style="display:table-cell;float:left;"><label for="codexproxyd_enable"><input id="codexproxyd_enable" class="switch" type="checkbox" style="display:none;"><div class="switch_container"><div class="switch_bar"></div><div class="switch_circle transition_style"><div></div></div></div></label></div></td></tr><tr><th>磁盘挂载点</th><td><select name="codexproxyd_disk_path_selected" id="codexproxyd_disk_path_selected" class="input_option" onchange="refresh_paths();"></select></td></tr><tr><th>镜像地址</th><td><input id="codexproxyd_image_ref" type="text" class="input_ss_table" style="width:96%;" value="" placeholder="例如: ghcr.io/example/codex-tools-proxyd:latest" /></td></tr><tr><th>DockRoot 路径</th><td class="ks_info"><code id="dockroot_bin">-</code></td></tr><tr><th>数据目录</th><td class="ks_info"><code id="data_dir">-</code></td></tr><tr><th>运行日志</th><td class="ks_info"><code id="runtime_log_path">-</code></td></tr><tr><th>Audit Log</th><td class="ks_info"><code id="audit_log_path">-</code></td></tr><tr><th>Error Log</th><td class="ks_info"><code id="error_log_path">-</code></td></tr><tr><th>操作</th><td><input class="button_gen" type="button" value="保存设置" onclick="onSaveSettings();" /><input class="button_gen" type="button" value="拉取/更新镜像" onclick="onAction('pull_image');" /><input class="button_gen" type="button" value="启动" onclick="onAction('start');" /><input class="button_gen" type="button" value="停止" onclick="onAction('stop');" /><input class="button_gen" type="button" value="重启" onclick="onAction('restart');" /><input class="button_gen" type="button" value="刷新 Key" onclick="onAction('regenerate_key');" /><input class="button_gen" type="button" value="删除容器" onclick="onAction('remove_container');" /></td></tr></table>
<div style="margin:20px 0 10px 5px;" class="splitLine"></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">账号导入</td></tr></thead><tr><th>导入模式</th><td><select id="codexproxyd_payload_kind" class="input_option"><option value="accounts_json">accounts.json</option><option value="auth_json">auth.json</option></select></td></tr><tr><th>粘贴内容</th><td><textarea id="codexproxyd_payload_text" class="ks_payload" spellcheck="false" placeholder="在这里粘贴 accounts.json 或完整 auth.json"></textarea></td></tr><tr><th>导入说明</th><td class="ks_info"><li>选择 <code>accounts.json</code> 时会直接校验并写入数据目录。</li><li>选择 <code>auth.json</code> 时，页面会先转换成单账号 <code>accounts.json</code>，再提交给插件保存。</li></td></tr><tr><th>导入操作</th><td><input class="button_gen" type="button" value="导入 accounts.json" onclick="onAction('import_accounts');" /><input class="button_gen" type="button" value="导入 auth.json" onclick="onAction('import_auth');" /></td></tr></table>
<div style="margin:20px 0 10px 5px;" class="splitLine"></div>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">运行日志</td></tr></thead><tr><th>日志尾部</th><td><textarea id="runtime_log" class="ks_runtime_log" readonly="readonly" spellcheck="false"></textarea></td></tr><tr><th>日志操作</th><td><input class="button_gen" type="button" value="刷新运行日志" onclick="refresh_runtime_log();" /></td></tr></table>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">Request Audit Log</td></tr></thead><tr><th>Recent Entries</th><td><textarea id="audit_log" class="ks_runtime_log" readonly="readonly" spellcheck="false"></textarea></td></tr><tr><th>Actions</th><td><input class="button_gen" type="button" value="Refresh Audit Log" onclick="refreshAuditLog();" /></td></tr></table>
<table width="100%" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#6b8fa3" class="FormTable"><thead><tr><td colspan="2">Error Log</td></tr></thead><tr><th>Recent Errors</th><td><textarea id="error_log" class="ks_runtime_log" readonly="readonly" spellcheck="false"></textarea></td></tr><tr><th>Actions</th><td><input class="button_gen" type="button" value="Refresh Error Log" onclick="refreshErrorLog();" /></td></tr></table>
<div style="margin:30px 0 10px 5px;" class="splitLine"></div></td></tr></table></td></tr></table></td><td width="10" align="center" valign="top"></td></tr></table><div id="footer"></div></body></html>
